spring:
  cloud:
    stream:
      bindings:
        dataInput:
          destination: testQueueDataExchange
          group: testQueueDataExchange-queue
      rabbit:
        bindings:
          dataInput:
            consumer:
              exchangeType: direct
              exchangeAutoDelete: false
              bindingRoutingKey: 'testRoutingKey'