version: 3
services:

  influxdb:
    image: docker.io/influxdb:1.7.10
    volumes:
      - influxdb2-data:/var/lib/influxdb2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: influxdb
      DOCKER_INFLUXDB_INIT_PASSWORD: influxdb
      DOCKER_INFLUXDB_INIT_ORG: spring-cloud-demo
      DOCKER_INFLUXDB_INIT_BUCKET: spring-cloud-demo
    restart: always

  postgresql:
    image: docker.io/postgres:13.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../resources/postgresql-init.d:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always

  mongodb:
    image: docker.io/mongo:4.4.4-bionic
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    restart: always

  mongo-express:
    image: docker.io/mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  grafana:
    image: docker.io/grafana/grafana:7.4.3
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000