eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  metrics:
    export:
      influx:
        enabled: true
        auto-create-db: true
        uri: "http://localhost:8086"
        user-name: influxdb
        password: influxdb