spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    publisher-confirm-type: correlated
    publisher-returns: true
  cloud:
    task:
      initialize-enabled: true
    bus:
      enabled: true
      refresh:
        enabled: true
      trace:
        enabled: true
    stream:
      rabbit:
        default:
          acknowledgeMode: AUTO
          autoBindDlq: true
          batchingEnabled: false
          bindQueue: true
          containerType: direct
          declareDlx: true
          declareExchange: true
          deliveryMode: PERSISTENT
          exchangeAutoDelete: true
          exchangeDurable: true
          exchangeType: direct
          lazy: false
          maxConcurrency: -1
          missingQueuesFatal: false
          prefetch: 1
          queueDeclarationRetries: 3
          quorum:
            enabled: false
        binder:
          adminAddresses: localhost:5672
          nodes: localhost:5672
      default:
        consumer:
          autoStartup: true
          partitioned: false
          maxAttempts: 3 # Will retry 2 times processing a message
          backOffInitialInterval: 1000
          backOffMultiplier: 2.0
          bindQueue: true
        producer:
          autoStartup: true
          bindQueue: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  metrics:
    web:
      server:
        auto-time-requests: true
    export:
      influx:
        enabled: true
        auto-create-db: true
        db: spring-cloud-demo
        uri: "http://localhost:8086"
        user-name: influxdb
        password: influxdb

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        amqp:
          rabbit: DEBUG
