spring:
  cloud:
    stream:
      bindings:
        dataOutput:
          destination: testQueueDataExchange
          group: testQueueDataExchange-queue
      rabbit:
        bindings:
          dataOutput:
            producer:
              exchangeType: direct
              routingKeyExpression: '''testRoutingKey'''

app:
  generatedCount: 10000
