eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  metrics:
    export:
      influx:
        db: spring-cloud-demo-eureka-server

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO